=== Moise25/Projet-BD/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- Declaration -->
    <xsd:element name="Etudiant">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="nom" type="xsd:string" ></xsd:element>
                <xsd:element name="prenom" type="xsd:string" ></xsd:element>
                <xsd:element name="n_i_e" type="xsd:int" ></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Projet">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="libelle" type="xsd:string" ></xsd:element>
                <xsd:element name="ultimatum" type="xsd:string" ></xsd:element>
                <xsd:element name="superviseur" type="xsd:string" ></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Schema -->
    <xsd:element name="reverse_engineering">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Etudiant"></xsd:element>
                <xsd:element ref="Projet"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Moise25/Projet-BD/xml/reverse_engineering.xml
<?xml version="1.0" encoding="UTF-8"  standalone="no" ?>

<reverse_engineering xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <Etudiant>
        <nom>Kh. Diaham</nom>
        <prenom>Amadou</prenom>
        <n_i_e>250</n_i_e>
    </Etudiant>
    <Projet>
        <libelle>XML/JSON -> SVG</libelle>
        <ultimatum>Doit etre livré après 3 semaines</ultimatum>
        <superviseur>M. A. B. MBACKE</superviseur>
    </Projet>
</reverse_engineering>
